note: fix the maximum allowed parameters error of sched_note_printf
64 bits = 5 bits (number) + 29 * 2 + 1 (unused)

nuttx/tools/mknotetype.py", line 244, in <module>
    note.generate_note_type_section(typefile, args.verbose)
  File "nuttx/tools/mknotetype.py", line 223, in generate_note_type_section
    type_bytes = typeflags.to_bytes(NOTE_TYPE_SIZE, byteorder=self.byteorder)
OverflowError: int too big to convert

Signed-off-by: yinshengkai <yinshengkai@xiaomi.com>