Revert "misc/rpmsgblk_server.c:340:36: error: ‘const struct block_operations’ has no member named ‘unlink’"
This reverts commit 76bd7241cce30198147925f153cf2e3c496ccb25.