arm64/cmake/toolchain: fix gccver & Wno compare
The -Wno-alloc-size-larger-than depend on GCCVER, should put after set
GCCVER, or will cause lost compile options
Add -Wno-stringop-overflow.

Causing:
include/libcxx/__memory/construct_at.h:41:10: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]

Signed-off-by: buxiasen <buxiasen@xiaomi.com>