fs/fatfs: fix compile error when enable fatfa option
Summary

   when we eanble FATFS option, a compile error occur at
arm64

fatfs/fatfs_vfs.c: In function 'fatfs_bind':
fatfs/fatfs_vfs.c:1135:16: error: format '%zd' \
 expects argument of type 'signed size_t',
but argument 3 has type 'int' [-Werror=format=]
 1135 |           ferr("Read failed: %zd\n", ret);
      |                ^~~~~~~~~~~~~~~~~~~~  ~~~
      |                                      |
      |                                      int
fatfs/fatfs_vfs.c:1135:32: note: format string is defined here
 1135 |           ferr("Read failed: %zd\n", ret);
      |                              ~~^
      |                                |
      |                                long int
      |                              %d
the ret is defined as int, change the format

Signed-off-by: qinwei1 <qinwei1@xiaomi.com>