drivers/crypto: fix compile error.
crypto/dev_urandom.c: In function 'devurandom_register':
 crypto/dev_urandom.c:317:16: error: variable 'seed' set but not used [-Werror=unused-but-set-variable]
 317 | unsigned int seed = 0;
 | ^~~~
 cc1: all warnings being treated as errors
 make[1]: *** [Makefile:113: dev_urandom.o] Error 1
 make[1]: Target 'libdrivers.a' not remade because of errors.
 make: *** [tools/LibTargets.mk:107: drivers/libdrivers.a] Error 2
 make: Target 'all' not remade because of errors.
 /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/tools/testbuild.sh: line 385: /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/../nuttx/nuttx.manifest: No such file or directory
 Normalize stm32f777zit6-meadow/usbnsh
 ====================================================================================

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>