Revert "Fix video/video.c:1458:52: error: implicit conversion from enumeration type 'enum v4l2_buf_type' to different enumeration type 'imgsensor_stream_type_t' (aka 'enum imgsensor_stream_type_e') [-Werror,-Wenum-conversion]"
This reverts commit 22f7fcbb5888531b0542903973d9d3ecb855da1a.

Reason for revert: have better patch