arm64/imx9: Fix imx9 compilation error.
make[1]: *** No rule to make target 'imx9_timer.c', needed by '.depend'.
make[1]: Target 'depend' not remade because of errors.
make: *** [tools/Unix.mk:630: pass2dep] Error 2
make: Target 'all' not remade because of errors.

Signed-off-by: v-tangmeng <v-tangmeng@xiaomi.com>