nuttx/libc:Add dl_iterate_phdr function.
When using the Ubuntu 20 system and enabling configuration cxx_exception, there may be linking issues, so we need add this function.

LD: nuttx.elf
ld: /usr/lib/gcc/x86_64-linux-gnu/13/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `_Unwind_Find_FDE':
(.text+0x277a): undefined reference to `dl_iterate_phdr'
(.text+0x277a): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `dl_iterate_phdr'

Signed-off-by: cuiziwei <cuiziwei@xiaomi.com>