serial/uart/h5: fix hci cmd error when splitting type and value
Signed-off-by: chengkai <chengkai@xiaomi.com>

wireless/bluetooth: fix ioctl no match driver param

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth:fix bt bridge acl data connect handle not match

bt bridge filter would not match when ACL in data
head with Packet_Boundary_Flag 0b10. in that case connect handle
is the first 3 octets of the packet, which not match
BT_HCI_EVT_LE_CONN_COMPLETE hci event alloc handle.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth:fix h5 ack to controller timeout

h5 ack which send to controller always timeout, which causing
controller would send repend hci data until host send back h5 ack.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: fix bt bridge would not filter vendor hci cmd

when downloading rtk firmware with vendor hci cmd sending to
bt bridge, which would not filter that hci cmd.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth:add bth5 with btslip and bth4

add bth5 with btslip and bth4, which will be more flexible in
btbridge or rpmsghci cases.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth:add btslip driver

add btslip driver.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth:add btslip checksum log for debug

add send btslip checksum log for debug

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth:support read imcompleted hci data from blueooth socket

hci data from bluetooth socket maybe imcompleted hci data.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: add nxmutex_lock check

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: check work_available with retxworker

retxworker would delay when there are many tx hci data

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: add slip SLIP_ESC case break

H5 SLIP_ESC magic payload whould be encode with
SLIP_ESC and SLIP_ESC_ESC

Signed-off-by: chengkai <chengkai@xiaomi.com>

gnu++20:fix build warning to [-Wmaybe-uninitialized].

17:10:41  wireless/bluetooth/bt_slip.c:300:7: error: 'byte' may be used uninitialized [-Werror=maybe-uninitialized]
17:10:41    300 |       wlerr("err: invalid escape byte %x\n", *byte);
17:10:41        |       ^
17:10:41  wireless/bluetooth/bt_slip.c: In function 'bt_slip_receive':
17:10:41  wireless/bluetooth/bt_slip.c:766:11: note: 'byte' was declared here
17:10:41    766 |   uint8_t byte;
17:10:41        |           ^~~~

Signed-off-by: cuiziwei <cuiziwei@xiaomi.com>

bluetooth: fix packet pointer may refer to null

rootcasue: when packet is null, packet var in for loop would
refer to null memory.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: fix dev->rxlen is considered to have possibly overflowed

rootcause: fix the expression dev->rxlen is considered to
have possibly overflowed.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: remove noblock mode handle

rootcause: move block and noblock handle to BTH4 handle.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: fix bt_slip_send would always block

rootcause: semcount maybe zero when nxsem_wait_uninterruptible

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: increase HCI RX buffer size.

BLUETOOTH_MAX_FRAMELEN  buffer size is only for LE only mode.
then we need to increase HCI buffer size in BR/EDR and LE mode.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: extract btuart_register interface

add btuart_create interface, which would be more
flexible in complex cases. And extract btuart_register interface.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: set bt_driver_register/unregister to xx_set/unset

change bt_driver_register/unregister function name to
bt_driver_set/unset, which would be prepared for bt_driver.h

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: add bt_driver_register interface

add bt_driver_register interface, which could handle
these cases:bth4 bth5 btbridge btslip and btuart_lowerhalf_s etc.

Signed-off-by: chengkai <chengkai@xiaomi.com>

bluetooth: call bt_driver_register common interface

Signed-off-by: chengkai <chengkai@xiaomi.com>

[bt_uart.c] fix bug:cant receive data

rootcause: in btuart_rxwork, read data in blocking mode and btuart_read do three times, maybe remote send some packets one time,so it wont read the sencond packets.

Signed-off-by: wangzhi7 <wangzhi7@xiaomi.com>

filter redundant hci reset commands due to dual Bluetooth protocol stacks

Signed-off-by: duqunbo <duqunbo@xiaomi.com>

serial: use dev references count make sure the driver only opened once

Signed-off-by: fangzhenwei <fangzhenwei@xiaomi.com>

add defconfig in nrf5340-dk:rpmsghci_sdc_cpunet.

Signed-off-by: chengkai <chengkai@xiaomi.com>

drivers: append bt_driver.c to bluetooth drivers Cmakelist.

Signed-off-by: fangzhenwei <fangzhenwei@xiaomi.com>

Add CONFIG_DRIVERS_BLUETOOTH=y, so 'bt_driver_register_with_id' can be linked.

Signed-off-by: chengkai <chengkai@xiaomi.com>