nrf52/serial: always compile nrf52_serial.c
So the up_putc function gets defined, just like most of other arch.

Fixed compile error:
nuttx/arch/arm/src/common/arm_nputs.c:44:(.text.up_nputs+0x12): undefined reference to `up_putc'

`Make.defs` has been modified before, this commit aligns `CMakeLists.txt`.

Signed-off-by: v-tangmeng <v-tangmeng@xiaomi.com>